name: first workflow 
on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3.6.0
            - name: Welcome Message
              run: echo "First workflow"
            - name: List Files
              run: ls
            - name: Read File
              run: cat README.md


