name: first workflow 
on: workflow_dispatch

jobs:
    first-job:
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v3.6.0
            - name: Welcome Message
              run: echo "First workflow from first job"
            - name: List Files
              run: ls
            - name: Read File
              run: cat README.md
            - name: Display OS
              run: echo "Running on ${{matrix.os}}"


